packaging:
  add:
    - target/${project.build.finalName}.jar
ports:
  - 8080
links:
  - elasticsearch
healthChecks:
  pings:
    - url: http://localhost:8080/
      timeout: 60000
tag:
    searchinabox/app:${project.version}